# Generated by Django 5.2.4 on 2025-07-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='heure_debut',
            field=models.TimeField(default='14:00:00'),
            preserve_default=False,
        ),
    ]
