# Generated by Django 5.2.4 on 2025-07-25 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_heure_debut'),
        ('salles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='gateau_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='type_reservation',
            field=models.CharField(choices=[('SALLE', 'Réservation de Salle'), ('GATEAU', 'Commande de Gâteau')], default='SALLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='duree_heures',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salles.salle'),
        ),
    ]
