# Generated by Django 5.2.4 on 2025-07-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('capacite', models.IntegerField()),
                ('categorie', models.CharField(choices=[('H', 'Salle pour Hommes'), ('F', 'Salle pour Femmes')], max_length=1)),
                ('prix_par_heure', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
