# Generated by Django 5.2.4 on 2025-07-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_salles/'),
        ),
    ]
