# Generated by Django 5.2.4 on 2025-07-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateaux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateau',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_gateaux/'),
        ),
    ]
