# Generated by Django 5.2.4 on 2025-07-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('photo', models.ImageField(upload_to='photos_produits/')),
                ('categorie', models.CharField(choices=[('BOISSON_CHAUDE', 'Boissons chaudes'), ('BOISSON_FROIDE', 'Boissons froides'), ('PATISSERIE', 'Pâtisseries'), ('SALE', 'Plats salés'), ('AUTRE', 'Autres')], max_length=20)),
            ],
            options={
                'verbose_name': 'produit du menu',
                'verbose_name_plural': 'produits du menu',
            },
        ),
    ]
